services:
  - type: web
    name: black-metal-transcription
    env: docker
    region: oregon
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000